# PostgreSQL + log4jdbc ??
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:postgresql://localhost:5432/testcasedb
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# JPA/Hibernate ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ???? ??? ?? (???)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# log4jdbc SQL ?? ??
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.sqltiming=INFO
logging.level.jdbc.audit=OFF
logging.level.jdbc.resultset=OFF
logging.level.jdbc.connection=OFF
log4jdbc.dump.sql.maxlinelength=0

# ?????? ??? ??
testcase.init.enabled=true
